### ISSUE TITLE
countDuplicates returns one less value than present

### ISSUE THREAD

**Issue by parkerhendo** [parkerhendo/sketch-scripts#1]
When I run the method `countDuplicates`, it doesn't to return the last value of the array passed to it.

**Code**
```
const countDuplicates = (arr, length) => {
  let sorted = arr.sort();
  let ref = arr[0];
  let count = 0;
  for (let i = 0; i < arr.length; i++) {
    if (ref === arr[i]) {
      count++;
    } else if (ref !== arr[i]) {
      console.log(`${ref}: ${count} times`);
      ref = arr[i];
      count = 0;
    }
  }
};
```
**Output**
array being passed `[ '#393294', '#859432', '#8b87c2', '#c25555' ]`
```
#393294: 9 times
#859432: 5 times
#8b87c2: 3 times
undefined
```
You can see **#c25555** is missing from the list.

What am I doing wrong here?

**Comment by hwanders** [comment]
You should use `sorted` instead of `arr`. In the loop you should reset the counter to 1 to actually count the first newly detected value. For correct logging of the last unique value you have to add a log after the loop too.

**Comment by parkerhendo** [comment]
@hwanders That was it! I was resetting `count` to 0 instead of 1. Thanks for the help!
